#!/bin/bash

me=$(basename $0)
function usage {
    echo "Usage:"
    echo "  $me <something>
    " 
    echo "example:"
    echo '#> bashrc-config-add gem'
    echo '#> bashrc-config-add node
    '
    
    echo "Following available:"
    grep 'function add' $0 | grep -v grep | awk '{print $2}'
}

OPT=$1

# GEM-environment:
function add_ruby {
    echo 'export GEM_HOME="$HOME/.gem"' >> ~/.bashrc
    echo 'export GEM_PATH="$HOME/.gem"' >> ~/.bashrc
    echo 'PATH=$PATH:.:$HOME/bin/:$HOME/.gem/bin/' >> ~/.bashrc
}

# Node Version Manager:
function add_nvm {
    echo ""
}

function add_aliases {
    echo '# git aliases ################################################################
#
alias fetch="git fetch -v"
alias gitone="git log --pretty=oneline"
alias gitoneline=gitone
alias gitpretty=gitone
alias gitlast="git diff HEAD^..HEAD"
alias gitlog="git log -p"
alias gitlogsum="git log --stat --summary"
alias stat="git status ; git stash list"
alias gitime="git log --pretty=format:'%h was %an, %ar, message: %s'"
alias gd="git diff"
alias gdc="git diff --cached"
alias changelog="git log > changelog"
alias gb="git branch -a"

    ' >> ~/.bashrc
}


# git-completition:
function add_git-completiotion {
    echo ""
}


function add_liqupmt {
    echo 'if [[ -e "$HOME/.liquidprompt/liquidprompt" ]]; then
    #export LP_ENABLE_BATT=1
    #export LP_PERCENT_ALWAYS=1
    #export LP_ENABLE_FQDN=1
    export LP_ENABLE_SUDO=1
    export LP_HOSTNAME_ALWAYS=1
    export LP_HOSTNAME_METHOD=full
    source ~/.liquidprompt/liquidprompt
    source ~/.liquidprompt/themes/powerline/powerline.theme 
    lp_theme powerline
fi' >> ~/.bashrc
}

case $OPT in 
    "ruby"|"gem") add_ruby;;
    "liquid") add_liqupmt ;;
    "alias"|"aliases") add_aliases;;
    *)
        echo "nothing to install."
        usage
    ;;
esac
